namespace AttendanceAppProject.ApiService.Data.Models;

// Attendance Instance class representing the AttendanceInstance relation, auto-generated by EFcore

public partial class AttendanceInstance
{
    public Guid AttendanceId { get; set; } // PK

    public string StudentId { get; set; } = null!; // FK

    public Guid ClassId { get; set; } // FK

	public string? IpAddress { get; set; }

	public bool? IsLate { get; set; }

	public bool? ExcusedAbsence { get; set; }

	public DateTime? DateTime { get; set; }

    // virtual classes are used by EFcore to model the database, we will not be interacting with these directly
    public virtual Class Class { get; set; } = null!;

	public virtual Student Student { get; set; } = null!;
}
