namespace AttendanceAppProject.ApiService.Data.Models;

// ClassSchedule class representing the AttendanceInstance relation, maps classes to timings, auto-generated by EFcore

public partial class ClassSchedule
{
    public Guid ClassScheduleId { get; set; } // PK

    public Guid ClassId { get; set; } // FK

	public string? DayOfWeek { get; set; }

	public virtual Class Class { get; set; } = null!;
}
