using System;
using System.Collections.Generic;

namespace AttendanceAppProject.ApiService.Data.Models;

// Password class representing the Password relation in the database, auto-generated by EFcore
public partial class Password
{
    public Guid PasswordId { get; set; } // PK 

    public Guid ClassId { get; set; } // FK

    public DateOnly? DateAssigned { get; set; }

    public string PasswordText { get; set; } = null!;

    public virtual Class Class { get; set; } = null!;
}
